name: Plexus
main: Plexus\Main
version: 0.1.3.7
api: 3.0.0-ALPHA9
load: STARTUP
author: ZeroDev
description: a core for plexus studio
commands:
 welcome:
 description: testing cmd for ui
 hub:
 description: sends a player back to spawn